### ISSUE TITLE
[Android] EventInfo.Time is set to year 0001 despite TimeStamp being set correctly on eventproperties

### ISSUE THREAD

**Issue by Yuncun** [microsoft/cpp_client_telemetry#1108]
**OneDrive Android** 
We are on [3.7.5.1 ](https://github.com/microsoft/cpp_client_telemetry/releases/tag/v3.7.5.1). We recently updated this version from 3.5.63, which is a massive update worth about two years of changes.

**Steps to reproduce.**
We are sending EventProperties to Logger with the timestamps correctly set to current time in milliseconds. This is what it looks like on our end. The second highlighted line shows `TimeStamp` correctly set with a millisecond time.

**What is the expected behavior?**
I expect that the value passed into `EventProperties.setTimestamp(long)` should be the time reflected in EventInfo.Time

**What is the actual behavior?**
`EventInfo.Time` is incorrect when the data is emitted and picked up in Aria. EventInfo.Time is showing a date in the year 0001. This causes our telemetry tools to reject the data.

This is what the data looks like when I receive it in Aria. I notice that there are two properties marked `TimeStamp`, with the inner `TimeStamp` value being set to a negative number Perhaps this is why EventInfo.Time is incorrect, although I do not know why this happens.

**Comment by Yuncun** [comment]
Here's a decoded request body from fiddler
[decoded_oneds_sample.txt](https://github.com/microsoft/cpp_client_telemetry/files/10904886/decoded_oneds_sample.txt)

![image](https://user-images.githubusercontent.com/1505391/223306188-bc646b63-310d-4e40-9d8c-da564b26076d.png)

I see `timeStamp` here but I do not see an "eventInfo.time".

**Comment by maxgolov** [comment]
cc: @kindbe @lalitb 

The value shown is treated by collector as time in ticks, not millis. If you take that time value and convert it as .NET ticks to time, you get exactly this date `0001-01-02`.

The fix should be in `EventPropertiesDecorator.hpp` to convert the value returned by `GetTimestamp()` from millis to .NET ticks. `time_t` should have a helper method for that. Collector expects the ticks, not millis in this field. 😊

In `BaseDecorator.cpp`:
`record.time = PAL::getUtcSystemTimeinTicks()`
This is correct. That's why all usual events have the right timestamps on them.

In `EventPropertiesDecorator.hpp`:
`record.time = timestamp`
This is incorrect. Because `timestamp` above is in millis, not ticks. #909 needs a minor fix.

**Comment by ThomsonTan** [comment]
For the millis, is there a well known start point of the milllis value? In [getUtcSystemTimeinTicks](https://github.com/microsoft/cpp_client_telemetry/blob/8032b1aef1931ed9027034a05b847598b5a20e7f/lib/pal/PAL.cpp#L390), Windows and Linux are handled differently.
