### ISSUE TITLE
Is ARM build supported for Windows?

### ISSUE THREAD

**Issue by yulin-li** [microsoft/cpp_client_telemetry#913]
Is ARM build supported for Windows?

I am using `win32-lib` project in the `MSTelemetrySDK` vs solution to build a static lib for my project. I found `win32-lib` project only support `x64`, `win32` and `arm64` platform. So, is arm build supported? I am wondering if it is just missed to add this platform to the project or arm build is totally not supported.

Thanks.

**Comment by lalitb** [comment]
I don't see a reason why this `arm` platform shouldn't be supported for the `win32-lib` build. Probably, there was no ask for this till now. From history, I can see @maxgolov added the support for `arm64'.

**Comment by maxgolov** [comment]
There are several practical reasons here:
- Qualcomm platforms (Win32 Desktop) are ARM64
- Most common PC platforms are x86 and x64
- even Qualcomm platforms may run x86 (on old builds of Windows 10) and x64 emulation (on newer builds of WIndows 10)

That leaves `arm` 32-bit rather unwanted and unpopular. We used to support that for Win 10 Phone, but this architecture is now obsolete. You may need to carefully review the practical need, where / why do you need to use 32-bit `arm` on Windows? Is this for Windows 10 IoT scenarios? Do these devices natively support `arm64`, and if so - wouldn't it be more prudent to build your app or service targeting `arm64` instead of arm 32-bit?

It's a matter of adding _unpopular_ build configuration, that otherwise really does not add much value overall. Something to discuss with community during one of weekly sync-up calls.

**Comment by maxgolov** [comment]
I think it'd be practical to follow the same guidelines as `dotnet` is following, as in `arm32 is not supported`. See https://github.com/dotnet/core/issues/5176

**Comment by yulin-li** [comment]
Thanks @lalitb and @maxgolov! We just support arm32 on windows but don't know any customer is using it. Looks there's no value to support arm32 for windows. I will add telemetry component to other platform and leave arm32 without change. And discuss with my team to see if we can drop windows arm32. Thanks for your information again.
