### ISSUE TITLE
Rename the default branch to main

### ISSUE THREAD

**Issue by reyang** [microsoft/cpp_client_telemetry#924]
This is a general movement from GitHub and Microsoft to use "main" as the default branch.

**Comment by lalitb** [comment]
Will communicate this in today's community meeting, and do the required changes.

**Comment by lalitb** [comment]
Planning to follow below steps for migration:

1. Add `main` branch to the list of branches used to trigger actions in github actions.
2. Notify in the "1DS C++ SDK community meeting" teams channel  - for other projects to be prepared for change if required.
2. Rename master branch to main ( Admin permission required ).  When triggered through the GitHub UI, this will automatically retarget any open pull requests to the new branch. Locally, developers will need to checkout the main branch and delete their local master branch.
3. Change all documentation/README links to point to the newly renamed branch instead of master. Also change the vspkg port [file ](https://github.com/microsoft/cpp_client_telemetry/blob/12c6d5530be29010efca03d0b78cf7ddd1093b54/tools/ports/mstelemetry/portfile.cmake#L31) for mstelemetry to use newly renamed branch.
4. Remove the master branch from the list of branches which trigger the github actions.
5. Modify github action for [cpp_client_telemetry_modules](https://github.com/microsoft/cpp_client_telemetry_modules/blob/665d5bb0fcc272d47a6956ed04787f4793a9cb11/.github/workflows/build-android-aar.yml#L22) to use this renamed branch while checking out main repo.
6. Notify  in the "1DS C++ SDK community meeting" teams channel for completion of this task.

Please comment here in case of any concerns.

**Comment by reyang** [comment]
I know there are consumers who set up their own CI job to pull from master branch, so they need to make the change.
To avoid breaking them (especially folks who might miss the community meeting), I think we can:
1. Rename master to branch to main (this keeps all the existing settings such as branch policy, so we don't have to recreate them)
2. Push main to master branch (just bring back the master branch), and keep it for two months (so folks downstream won't see an immediate HTTP 404). And we should also make sure that master branch is locked so we don't allow any update their (to motivate people from moving to main)
3. After two months, delete the master branch

**Comment by lalitb** [comment]
Good point. This is how to steps look like ( added step 4 )

1. Add main branch to the list of branches used to trigger actions in github actions.
2. Notify in the "1DS C++ SDK community meeting" teams channel - for other projects to be prepared for change if required.
3. Rename master branch to main ( Admin permission required ). When triggered through the GitHub UI, this will automatically retarget any open pull requests to the new branch. Locally, developers will need to checkout the main branch and delete their local master branch.
4. Push main to master branch. Lock the newly created master, and keep it for two months.
5. Change all documentation/README links to point to the newly renamed branch instead of master. Also change the vspkg port file for mstelemetry to use newly renamed branch.
6. Remove the master branch from the list of branches which trigger the github actions.
7. Modify github action for cpp_client_telemetry_modules to use this renamed branch while checking out main repo.
8. Notify in the "1DS C++ SDK community meeting" teams channel for completion of this task.
9. Keep sending occasional reminder in community channel to start using `main` branch.

After two months:
1. Final reminder in the community channel for deletion of `master` branch.
1. If no concerns raised by any team, delete the master branch.

Please comment here in case of any concerns.

**Comment by lalitb** [comment]
closing this as we have moved to `main` branch.
