### ISSUE TITLE
Use of new 'PauseActivity' and 'WaitPause' in a UWP suspend step of app lifecycle?

### ISSUE THREAD

**Issue by Jamatth** [microsoft/cpp_client_telemetry#978]
I see that the newest release includes a doc cpp_client_telemetry/docs/use-after-free.md that mentions new methods for eliminating race conditions during app shutdown.  I'm wondering if you have also seen the same race condition during the suspend process of a UWP app (https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle)

The app I work on sometimes sees crashes due to the suspend process taking too long so the OS kills the app.  The doc added states the most common crash is a read-dereference, but if you have seen issues with this SDK due to perhaps unsent telemetry messages during an app suspend, maybe these new methods could help us avoid some of these crashes.

**Comment by lalitb** [comment]
> The app I work on sometimes sees crashes due to the suspend process taking too long so the OS kills the app.

**Comment by lalitb** [comment]
> The app I work on sometimes sees crashes due to the suspend process taking too long so the OS kills the app. 

Do you mean the app is taking a long time to suspend, possibly because it is still transmission the telemetry events, and so the OS kills the app?

**Comment by maxgolov** [comment]
Make sure when you suspend, you do not perform `FlushAndTeardown`. You must also request deferral from UWP while you run `PauseTransmission`+`Flush` and `ResumeTransmission` after. This historically worked well. This is for C#, but C++ should have the same APIs available:

https://github.com/microsoft/cpp_client_telemetry/blob/fcd3b5219abf25c958c9621f64105a9f6a5122f4/examples/cs/SampleCsUWP/App.xaml.cs#L239

Adjust the code though to avoid upload, because it'd be best to `PauseTransmission` rather than resume when you are being suspended. Resuming and trying to upload - results in non-deterministic network I/O delay, whereas flushing on disk with paused transmission should generally be fast.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/34072974/146617364-a0b5dceb-726e-48cf-bf9f-3a1231e23485.png">

**Comment by lalitb** [comment]
@Jamatth - do you have any further questions, or this can be closed?
